apiVersion: v2
name: cloudnative-pg
description: CloudNativePG Operator Helm Chart
home: https://cloudnative-pg.io
icon: https://raw.githubusercontent.com/cloudnative-pg/artwork/main/cloudnativepg-logo.svg
sources:
  - https://github.com/cloudnative-pg/charts
dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.26.1

type: application

# renovate: datasource=helm depName=cloudnative-pg repository=https://cloudnative-pg.github.io/charts
version: "0.26.0"

# renovate: datasource=github-releases depName=cloudnative-pg/cloudnative-pg
appVersion: v1.27.1

keywords:
  - operator
  - controller
  - postgresql
  - postgres
  - database
